### ISSUE TITLE
Configure dosnt't look up for libgc headers

### ISSUE THREAD

**Issue by yashrk** [wingo/fibers#106]
Ubuntu 23.10, fibers 1.3.1.

The `./configure` command finishes OK, but the `make` command fails with the following:
```
make[1]: Entering directory '/home/yshirokov/src/tools/fibers-1.3.1'
/bin/bash ./libtool  --tag=CC   --mode=link gcc -I. -Wall -Werror  -I/usr/local/include/guile/3.0  -I./extensions -g -O2 -export-dynamic -module  -o fibers-epoll.la -rpath /usr/local/lib/guile/3.0/extensions extensions/fibers_epoll_la-epoll.lo -L/usr/local/lib -lguile-3.0 -lgc -lpthread -ldl   
libtool: link: gcc -shared  -fPIC -DPIC  extensions/.libs/fibers_epoll_la-epoll.o   -L/usr/local/lib /usr/local/lib/libguile-3.0.so -lgc -lpthread -ldl  -g -O2   -Wl,-soname -Wl,fibers-epoll.so.0 -o .libs/fibers-epoll.so.0.0.0
/usr/bin/ld: cannot find -lgc: No such file or directory
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:706: fibers-epoll.la] Error 1
make[1]: Leaving directory '/home/yshirokov/src/tools/fibers-1.3.1'
```

Installation of `libgc-dev` package, obviously, allows to build the library.

**Comment by emixa-d** [comment]
I don't see anything about headers in that message.

AFAICT, fibers doesn't directly use libgc anywhere. It seems to only uses libgc through guile. Fibers' configure script uses Guile via `GUILE_PKG` (which in turn uses pkg-config). So I expect the bug to be any of:

 * Guile's pkg-config file doesn't refer to libgc properly.
 * Guile's pkg-config file does refer to libgc properly, but Ubuntu's guile-dev doesn't depend on libguile-dev properly
 * pkg-config is broken (I expect this not to be the case, including this for completeness)
 * the local copy guile.m4 is outdated (try updating it?) (*)
 * even more recent guile.m4 do something incorrect here.

**Comment by emixa-d** [comment]
Do you have `guile-3.0-dev` installed?

**Comment by yashrk** [comment]
I don't have an Ubuntu machine right now, on my current Linux `.pc` file for Guile contains `-lgc`. Will check on some Ubuntu installation when it will be possible.

**Comment by emixa-d** [comment]
I think you'll have a better chance at resolving this anomaly by sending a bug report to the distro (for the guile-3.0 package, perhaps after some minimisation) instead of here.

**Comment by yashrk** [comment]
Ok, looks like not a fibers build scripts bug indeed.
