### ISSUE TITLE
Q: Does it support racket? or how to use it in racket

### ISSUE THREAD

**Issue by Yanhao** [wingo/fibers#107]

**Comment by LiberalArtist** [comment]
This is a Guile library that implements Concurrent ML primitives. Racket's built-in support for concurrency is also based on Concurrent ML: here are the introductory [guide](https://docs.racket-lang.org/guide/concurrency.html) and the [reference](https://docs.racket-lang.org/reference/sync.html) manual.

**Comment by emixa-d** [comment]
There's no bug report here and the question has been answered, so closing.
