### ISSUE TITLE
autoreconf -vif fails complaining about possibly undefined macro: AC_LIB_LINKFLAGS_FROM_LIBS

### ISSUE THREAD

**Issue by vyp** [wingo/fibers#17]
```
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
aclocal: warning: couldn't open directory 'm4': No such file or directory
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: copying file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
autoreconf: running: /nix/store/wd3fssfnj4ywzwwcym7fjbxywhbfr8cc-autoconf-2.69/bin/autoconf --force
configure:13082: error: possibly undefined macro: AC_LIB_LINKFLAGS_FROM_LIBS
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /nix/store/wd3fssfnj4ywzwwcym7fjbxywhbfr8cc-autoconf-2.69/bin/autoconf failed with exit status: 1
```

So autoconf doesn't have gnulib, which is where `AC_LIB_LINKFLAGS_FROM_LIBS` is defined. I'm not sure what to do now.

I know that for example other projects have `bootstrap` scripts that allow setting a `--gnulib-srcdir`, probably generated from a [bootstrap.conf file](https://github.com/fontforge/fontforge/blob/20d67b0c43db2815d676af23d74317b9fd17dc1f/bootstrap.conf) somehow?

https://github.com/fontforge/fontforge/blob/20d67b0c43db2815d676af23d74317b9fd17dc1f/bootstrap#L4573-L4578

**Comment by vyp** [comment]
I opened this too soon, I figured it out.

**Comment by HolgerPeters** [comment]
@vyp so what was your solution?

**Comment by mrosset** [comment]
On guix this error can fixed by installing gettext which provides lib-link.m4 where AC_LIB_LINKFLAGS_FROM_LIBS is defined. I'm not sure if this is the best way to fix this.
