### ISSUE TITLE
Installation steps not working

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [wingo/fibers#20]
I just tried to install the fibers library, but something is not working correctly. After installing I cannot use the module: `(use-modules (fibers))`. If I try, I get the following error:

    scheme@(guile-user)> (use-modules (fibers))
    While compiling expression:
    no code for module (fibers)

Here are my outputs of the single commands from the installation instructions:

    $ ./configure --prefix=/opt/guile
    checking for a BSD-compatible install... /usr/bin/install -c
    checking whether build environment is sane... yes
    checking for a thread-safe mkdir -p... /bin/mkdir -p
    checking for gawk... gawk
    checking whether make sets $(MAKE)... yes
    checking whether make supports nested variables... yes
    checking for style of include used by make... GNU
    checking for gcc... gcc
    checking whether the C compiler works... yes
    checking for C compiler default output file name... a.out
    checking for suffix of executables... 
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
    checking whether gcc accepts -g... yes
    checking for gcc option to accept ISO C89... none needed
    checking whether gcc understands -c and -o together... yes
    checking dependency style of gcc... gcc3
    checking for library containing strerror... none required
    checking for gcc... (cached) gcc
    checking whether we are using the GNU C compiler... (cached) yes
    checking whether gcc accepts -g... (cached) yes
    checking for gcc option to accept ISO C89... (cached) none needed
    checking whether gcc understands -c and -o together... (cached) yes
    checking dependency style of gcc... (cached) gcc3
    checking how to run the C preprocessor... gcc -E
    checking for grep that handles long lines and -e... /bin/grep
    checking for egrep... /bin/grep -E
    checking for ANSI C header files... yes
    checking build system type... x86_64-pc-linux-gnu
    checking host system type... x86_64-pc-linux-gnu
    checking how to print strings... printf
    checking for a sed that does not truncate output... /bin/sed
    checking for fgrep... /bin/grep -F
    checking for ld used by gcc... /usr/bin/ld
    checking if the linker (/usr/bin/ld) is GNU ld... yes
    checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
    checking the name lister (/usr/bin/nm -B) interface... BSD nm
    checking whether ln -s works... yes
    checking the maximum length of command line arguments... 1572864
    checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
    checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
    checking for /usr/bin/ld option to reload object files... -r
    checking for objdump... objdump
    checking how to recognize dependent libraries... pass_all
    checking for dlltool... no
    checking how to associate runtime and link libraries... printf %s\n
    checking for ar... ar
    checking for archiver @FILE support... @
    checking for strip... strip
    checking for ranlib... ranlib
    checking command to parse /usr/bin/nm -B output from gcc object... ok
    checking for sysroot... no
    checking for a working dd... /bin/dd
    checking how to truncate binary pipes... /bin/dd bs=4096 count=1
    checking for mt... mt
    checking if mt is a manifest tool... no
    checking for sys/types.h... yes
    checking for sys/stat.h... yes
    checking for stdlib.h... yes
    checking for string.h... yes
    checking for memory.h... yes
    checking for strings.h... yes
    checking for inttypes.h... yes
    checking for stdint.h... yes
    checking for unistd.h... yes
    checking for dlfcn.h... yes
    checking for objdir... .libs
    checking if gcc supports -fno-rtti -fno-exceptions... no
    checking for gcc option to produce PIC... -fPIC -DPIC
    checking if gcc PIC flag -fPIC -DPIC works... yes
    checking if gcc static flag -static works... yes
    checking if gcc supports -c -o file.o... yes
    checking if gcc supports -c -o file.o... (cached) yes
    checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
    checking whether -lc should be explicitly linked in... no
    checking dynamic linker characteristics... GNU/Linux ld.so
    checking how to hardcode library paths into programs... immediate
    checking whether stripping libraries is possible... yes
    checking if libtool supports shared libraries... yes
    checking whether to build shared libraries... yes
    checking whether to build static libraries... no
    checking sys/epoll.h usability... yes
    checking sys/epoll.h presence... yes
    checking for sys/epoll.h... yes
    checking for epoll_create... yes
    checking for epoll_create1... yes
    checking for pkg-config... /usr/bin/pkg-config
    checking pkg-config is at least version 0.9.0... yes
    configure: checking for guile 3.0
    configure: checking for guile 2.2
    configure: found guile 2.2
    checking for ld used by gcc... /usr/bin/ld -m elf_x86_64
    checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
    checking for shared library run path origin... done
    checking for GUILE... yes
    checking for guile-2.2... no
    checking for guile2.2... no
    checking for guile-2... no
    checking for guile2... no
    checking for guile... /usr/local/bin/guile
    checking for Guile version >= 2.2... 2.2.3
    checking for guild... /usr/local/bin/guild
    checking for guile-config... /usr/local/bin/guile-config
    checking that generated files are newer than configure... done
    configure: creating ./config.status
    config.status: creating env
    config.status: creating Makefile
    config.status: creating config.h
    config.status: config.h is unchanged
    config.status: executing depfiles commands
    config.status: executing libtool commands

Then

    $ make
    mkdir -p fibers
    sed -e "s|@extlibdir\@|/opt/guile/lib/guile/2.2/extensions|" \
        ./fibers/config.scm.in > fibers/config.scm
    make  all-am
    make[1]: Entering directory '/home/user/development/GuileScheme/fibers'
    /bin/bash ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.    -I. -Wall -Werror  -pthread -I/usr/local/include/guile/2.2 -g -O2 -MT epoll_la-epoll.lo -MD -MP -MF .deps/epoll_la-epoll.Tpo -c -o epoll_la-epoll.lo `test -f 'epoll.c' || echo './'`epoll.c
    libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I. -Wall -Werror -pthread -I/usr/local/include/guile/2.2 -g -O2 -MT epoll_la-epoll.lo -MD -MP -MF .deps/epoll_la-epoll.Tpo -c epoll.c  -fPIC -DPIC -o .libs/epoll_la-epoll.o
    mv -f .deps/epoll_la-epoll.Tpo .deps/epoll_la-epoll.Plo
    /bin/bash ./libtool  --tag=CC   --mode=link gcc -I. -Wall -Werror  -pthread -I/usr/local/include/guile/2.2 -g -O2 -export-dynamic -module  -o epoll.la -rpath /opt/guile/lib/guile/2.2/extensions epoll_la-epoll.lo -L/usr/local/lib -lguile-2.2 -lgc  
    libtool: link: gcc -shared  -fPIC -DPIC  .libs/epoll_la-epoll.o   -L/usr/local/lib /usr/local/lib/libguile-2.2.so -L/usr/lib/x86_64-linux-gnu -lffi -lunistring -lgmp /usr/lib/x86_64-linux-gnu/libltdl.so -ldl -lcrypt -lm -lgc  -pthread -g -O2   -pthread -Wl,-soname -Wl,epoll.so.0 -o .libs/epoll.so.0.0.0
    libtool: link: (cd ".libs" && rm -f "epoll.so.0" && ln -s "epoll.so.0.0.0" "epoll.so.0")
    libtool: link: (cd ".libs" && rm -f "epoll.so" && ln -s "epoll.so.0.0.0" "epoll.so")
    libtool: link: ( cd ".libs" && rm -f "epoll.la" && ln -s "../epoll.la" "epoll.la" )
    ./env /usr/local/bin/guild compile -Wunbound-variable -Warity-mismatch -Wformat -o "fibers.go" "fibers.scm"
    wrote `fibers.go'
    ./env /usr/local/bin/guild compile -Wunbound-variable -Warity-mismatch -Wformat -o "fibers/channels.go" "fibers/channels.scm"
    wrote `fibers/channels.go'
    ./env /usr/local/bin/guild compile -Wunbound-variable -Warity-mismatch -Wformat -o "fibers/conditions.go" "fibers/conditions.scm"
    wrote `fibers/conditions.go'
    ./env /usr/local/bin/guild compile -Wunbound-variable -Warity-mismatch -Wformat -o "fibers/config.go" "fibers/config.scm"
    wrote `fibers/config.go'
    ./env /usr/local/bin/guild compile -Wunbound-variable -Warity-mismatch -Wformat -o "fibers/counter.go" "fibers/counter.scm"
    wrote `fibers/counter.go'
    ./env /usr/local/bin/guild compile -Wunbound-variable -Warity-mismatch -Wformat -o "fibers/deque.go" "fibers/deque.scm"
    wrote `fibers/deque.go'
    ./env /usr/local/bin/guild compile -Wunbound-variable -Warity-mismatch -Wformat -o "fibers/epoll.go" "fibers/epoll.scm"
    wrote `fibers/epoll.go'
    ./env /usr/local/bin/guild compile -Wunbound-variable -Warity-mismatch -Wformat -o "fibers/interrupts.go" "fibers/interrupts.scm"
    wrote `fibers/interrupts.go'
    ./env /usr/local/bin/guild compile -Wunbound-variable -Warity-mismatch -Wformat -o "fibers/nameset.go" "fibers/nameset.scm"
    wrote `fibers/nameset.go'
    ./env /usr/local/bin/guild compile -Wunbound-variable -Warity-mismatch -Wformat -o "fibers/operations.go" "fibers/operations.scm"
    wrote `fibers/operations.go'
    ./env /usr/local/bin/guild compile -Wunbound-variable -Warity-mismatch -Wformat -o "fibers/posix-clocks.go" "fibers/posix-clocks.scm"
    wrote `fibers/posix-clocks.go'
    ./env /usr/local/bin/guild compile -Wunbound-variable -Warity-mismatch -Wformat -o "fibers/psq.go" "fibers/psq.scm"
    wrote `fibers/psq.go'
    ./env /usr/local/bin/guild compile -Wunbound-variable -Warity-mismatch -Wformat -o "fibers/scheduler.go" "fibers/scheduler.scm"
    wrote `fibers/scheduler.go'
    ./env /usr/local/bin/guild compile -Wunbound-variable -Warity-mismatch -Wformat -o "fibers/stack.go" "fibers/stack.scm"
    wrote `fibers/stack.go'
    ./env /usr/local/bin/guild compile -Wunbound-variable -Warity-mismatch -Wformat -o "fibers/repl.go" "fibers/repl.scm"
    wrote `fibers/repl.go'
    ./env /usr/local/bin/guild compile -Wunbound-variable -Warity-mismatch -Wformat -o "fibers/timers.go" "fibers/timers.scm"
    wrote `fibers/timers.go'
    ./env /usr/local/bin/guild compile -Wunbound-variable -Warity-mismatch -Wformat -o "fibers/web/server.go" "fibers/web/server.scm"
    wrote `fibers/web/server.go'
    ./env /usr/local/bin/guild compile -Wunbound-variable -Warity-mismatch -Wformat -o "web/server/fibers.go" "web/server/fibers.scm"
    wrote `web/server/fibers.go'
    make[1]: Leaving directory '/home/user/development/GuileScheme/fibers'

Then

    $ sudo make install
    make  install-am
    make[1]: Entering directory '/home/user/development/GuileScheme/fibers'
    make[2]: Entering directory '/home/user/development/GuileScheme/fibers'
    make[2]: Nothing to be done for 'install-exec-am'.
     /bin/mkdir -p '/opt/guile/lib/guile/2.2/extensions'
     /bin/bash ./libtool   --mode=install /usr/bin/install -c   epoll.la '/opt/guile/lib/guile/2.2/extensions'
    libtool: install: /usr/bin/install -c .libs/epoll.so.0.0.0 /opt/guile/lib/guile/2.2/extensions/epoll.so.0.0.0
    libtool: install: (cd /opt/guile/lib/guile/2.2/extensions && { ln -s -f epoll.so.0.0.0 epoll.so.0 || { rm -f epoll.so.0 && ln -s epoll.so.0.0.0 epoll.so.0; }; })
    libtool: install: (cd /opt/guile/lib/guile/2.2/extensions && { ln -s -f epoll.so.0.0.0 epoll.so || { rm -f epoll.so && ln -s epoll.so.0.0.0 epoll.so; }; })
    libtool: install: /usr/bin/install -c .libs/epoll.lai /opt/guile/lib/guile/2.2/extensions/epoll.la
    libtool: finish: PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/sbin" ldconfig -n /opt/guile/lib/guile/2.2/extensions
    ----------------------------------------------------------------------
    Libraries have been installed in:
       /opt/guile/lib/guile/2.2/extensions

    If you ever happen to want to link against installed libraries
    in a given directory, LIBDIR, you must either use libtool, and
    specify the full pathname of the library, or use the '-LLIBDIR'
    flag during linking and do at least one of the following:
       - add LIBDIR to the 'LD_LIBRARY_PATH' environment variable
         during execution
       - add LIBDIR to the 'LD_RUN_PATH' environment variable
         during linking
       - use the '-Wl,-rpath -Wl,LIBDIR' linker flag
       - have your system administrator add LIBDIR to '/etc/ld.so.conf'

    See any operating system documentation about shared libraries for
    more information, such as the ld(1) and ld.so(8) manual pages.
    ----------------------------------------------------------------------
     /bin/mkdir -p '/opt/guile/share/info'
     /usr/bin/install -c -m 644 ./fibers.info '/opt/guile/share/info'
     install-info --info-dir='/opt/guile/share/info' '/opt/guile/share/info/fibers.info'
     /bin/mkdir -p '/opt/guile/share/guile/site/2.2'
     /bin/mkdir -p '/opt/guile/share/guile/site/2.2/fibers/web'
     /usr/bin/install -c -m 644  fibers/web/server.scm '/opt/guile/share/guile/site/2.2/fibers/web'
     /bin/mkdir -p '/opt/guile/share/guile/site/2.2/web/server'
     /usr/bin/install -c -m 644  web/server/fibers.scm '/opt/guile/share/guile/site/2.2/web/server'
     /usr/bin/install -c -m 644  fibers.scm '/opt/guile/share/guile/site/2.2/.'
     /bin/mkdir -p '/opt/guile/share/guile/site/2.2/fibers'
     /usr/bin/install -c -m 644  fibers/channels.scm fibers/conditions.scm fibers/config.scm fibers/counter.scm fibers/deque.scm fibers/epoll.scm fibers/interrupts.scm fibers/nameset.scm fibers/operations.scm fibers/posix-clocks.scm fibers/psq.scm fibers/scheduler.scm fibers/stack.scm fibers/repl.scm fibers/timers.scm '/opt/guile/share/guile/site/2.2/fibers'
     /bin/mkdir -p '/opt/guile/lib/guile/2.2/ccache'
     /bin/mkdir -p '/opt/guile/lib/guile/2.2/ccache/fibers/web'
     /usr/bin/install -c -m 644  fibers/web/server.go '/opt/guile/lib/guile/2.2/ccache/fibers/web'
     /bin/mkdir -p '/opt/guile/lib/guile/2.2/ccache/web/server'
     /usr/bin/install -c -m 644  web/server/fibers.go '/opt/guile/lib/guile/2.2/ccache/web/server'
     /usr/bin/install -c -m 644  fibers.go '/opt/guile/lib/guile/2.2/ccache/.'
     /bin/mkdir -p '/opt/guile/lib/guile/2.2/ccache/fibers'
     /usr/bin/install -c -m 644  fibers/channels.go fibers/conditions.go fibers/config.go fibers/counter.go fibers/deque.go fibers/epoll.go fibers/interrupts.go fibers/nameset.go fibers/operations.go fibers/posix-clocks.go fibers/psq.go fibers/scheduler.go fibers/stack.go fibers/repl.go fibers/timers.go '/opt/guile/lib/guile/2.2/ccache/fibers'
    make[2]: Leaving directory '/home/user/development/GuileScheme/fibers'
    make[1]: Leaving directory '/home/user/development/GuileScheme/fibers'

What might seem unusual is, that it installs the library into `/opt/guile/lib/guile/2.2/extensions`, while I am using Guile `2.2.3`. Not sure if there should be another subdirectory in `/opt/guile/lib/guile/` for `2.2.3`.

However, `./env guile` works. There I can do `(use-modules (fibers))`.

The operating system is a Ubuntu 17.04.
Guile was build very recently, maybe 3 or 4 days ago.

**Comment by amirouche** [comment]
I think the guile your run doesn't look where you installed `fibers`. Try the following in a console:

```
$ guile -c "(display %load-path)"
```

**Comment by ZelphirKaltstahl** [comment]
Hey thanks for such a quick reply!
I was able to reproduce the issue at another machine (Xubuntu 16.04 here).
Maybe it's a general Ubuntu Guile Scheme setup issue, when installing Guile Scheme from source?

    $ guile -c "(display %load-path)"
    (/usr/local/share/guile/2.2 /usr/local/share/guile/site/2.2 /usr/local/share/guile/site /usr/local/share/guile)

Should I use another prefix for the configure step then?

**Comment by ZelphirKaltstahl** [comment]
I figured it out now. Apparently I should not add any parameters to `./configure` and then it works (using `/usr/local` to install). I thought I had thoroughly tried that before, not sure what I have been missing then.

**Comment by amirouche** [comment]
Please close the issue if everything is ok :)
