### ISSUE TITLE
Sending lambda as message does not work

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [wingo/fibers#22]
I have the following simplified code adapted from the tutorial:

    (use-modules (fibers)
                 (fibers channels)
                 (ice-9 match))

    (define (server in out)
      (let lopo ()
        (display (simple-format #f "~s" ((get-message in))))
        (put-message out 'pong!)
        (lopo)))

    (define (client in out)
      (put-message out (λ () 'ping!))
      (pk 'client-received (get-message in)))

    (run-fibers
     (lambda ()
       (let ([c2s (make-channel)]
             [s2c (make-channel)])
         (spawn-fiber (lambda () (server c2s s2c)))
         (client s2c c2s))))

However, when I run it, I get:

    Uncaught exception in task:
    In fibers.scm:
        149:8  2 (_)
    In /home/user/development/GuileScheme/fibers-tutorial/fibers-tutorial.scm:
        13:32  1 (server #<<channel> getq: #<atomic-box 5566f1ed9240 value: (())> getq-gc-c…> …)
    In unknown file:
               0 (_)
    ERROR: Wrong type to apply: ping!

I tried several versions of calling and not calling the received lambda, but it seems, that I cannot send a lambda?
That would mean though, that the procedures run in fibers need to be known / in some way defined ahead of receiving messages (only possible to receive data). I would like to be able to simply send a thunk to evaluate to a fiber.

**Comment by ZelphirKaltstahl** [comment]
I think the problem in this case was a superfluous pair of parentheses around the `(get-message in)` in the `server` definition. Closing this now, as I finally understood the error message.

**Comment by aconchillo** [comment]
Right, that looks like it. Thanks for closing this!
