### ISSUE TITLE
Resource (fd) leak in run-fibers

### ISSUE THREAD

**Issue by Reepca** [wingo/fibers#36]
Only the main scheduler is destroyed when run-fibers returns. So the epoll file descriptor and the two wake-pipe file descriptors for each remote scheduler stay open until garbage-collected (which until recently still wouldn't close them due to a guile bug with revealed-count).

To see this behavior in practice, call run-fibers in a loop a few thousand times (with `#:parallelism` > 1). Guile will abort when it tries creating a new thread but creating the sleep pipe for them returns EMFILE.

We should destroy the peer schedulers as well when we return from run-fibers. AFAIK this should be as simple as changing

    (match affinities
      ((affinity . affinities)
       (dynamic-wind
         (lambda ()
           (start-auxiliary-threads scheduler hz finished? affinities))
         (lambda ()
           (%run-fibers scheduler hz finished? affinity))
         (lambda ()
           (stop-auxiliary-threads scheduler)))))
    (destroy-scheduler scheduler)
    (apply values (atomic-box-ref ret))

to

    (match affinities
      ((affinity . affinities)
       (dynamic-wind
         (lambda ()
           (start-auxiliary-threads scheduler hz finished? affinities))
         (lambda ()
           (%run-fibers scheduler hz finished? affinity))
         (lambda ()
           (stop-auxiliary-threads scheduler)))))
    (for-each destroy-scheduler (scheduler-remote-peers scheduler))
    (destroy-scheduler scheduler)
    (apply values (atomic-box-ref ret))

It should be safe to destroy them at that point because `stop-auxiliary-threads` has ensured that they aren't running.

**Comment by linas** [comment]
You state:
> So the epoll file descriptor and the two wake-pipe file descriptors for each remote scheduler stay open until garbage-collected (which until recently still wouldn't close them due to a guile bug with revealed-count).

When was this fixed? I'm running guile-3.0.1 which comes as default with ubuntu focal 20.04 and I might be hitting the same bug in issue #52 ... but calling `(gc)` repeatedly does not clear it for me.

**Comment by Reepca** [comment]
See bug #41204 (https://lists.nongnu.org/archive/html/bug-guile/2020-05/msg00014.html), specifically

"Fixed in b1bdd791cefa1b6d113f9b3972550342d8f4aa9f.
Guile up to 2.2.7/3.0.2 included (but not 2.0) would thus leak the file descriptors of all the file ports not explicitly closed."

**Comment by aconchillo** [comment]
@Reepca do you mind creating a PR with this fix? I'll merge it. Planning to release 1.1.0 next week or after we merge this. Thanks!
