### ISSUE TITLE
Example from the manual doesn't work as documented

### ISSUE THREAD

**Issue by kromka-chleba** [wingo/fibers#43]
Guile version: 3.0.4
Fibers version: 1.0.0

```
     For example:
          (run-fibers (lambda () 1))
          => 1

          (run-fibers
           (lambda ()
             (spawn-fiber (lambda () (display "hey!\n")))))
          -| hey!

```
If I paste this into repl, it doesn't print "hey!". Adding #:drain? #t fixes the problem.

**Comment by aconchillo** [comment]
Thank you! In this case it needs `#:drain?` to let the fiber finish.
