### ISSUE TITLE
Unknown meta command: fibers

### ISSUE THREAD

**Issue by linas** [wingo/fibers#51]
The documentation mentions `2.6 REPL Commands`  -- `REPL Command: fibers [sched]` but when I run it I get
```
scheme@(run)> ,fibers
Unknown meta command: fibers
```
 FYI, I also have this:
```
scheme@(run)> ,scheds                    
No schedulers.
```
But that is OK, as expected because the scheduler has finished.

FYI, This is built from `git clone` of today's git repo.

**Comment by aconchillo** [comment]
There is no meta command for `,fibers` documented in the manual. There is `,help fibers` and load the module `(fibers)` but no reference to `,fibers`. Closing. Please, re-open if I'm misunderstanding.

**Comment by linas** [comment]
OK, yes, I looked just now at 

https://github.com/wingo/fibers/wiki/Manual#REPL-Commands

and indeed it is gone.
