### ISSUE TITLE
epoll instance is dead

### ISSUE THREAD

**Issue by emixa-d** [wingo/fibers#61]
Currently minimising my test case ...

**Comment by emixa-d** [comment]
Minimal test case:

```
(use-modules (fibers) (fibers conditions) (fibers scheduler))

(define c (make-condition))
(run-fibers
 (lambda ()
   (spawn-fiber (lambda () (wait c)))
   (yield-current-task)) ; let the other fiber wait forever
 #:hz 0 #:parallelism 1) ; it fails both with and without, preemption is another complication, so keep things simple for now by not preempting

(signal-condition! c)
```

**Comment by emixa-d** [comment]
Description:

When a fiber is waiting on a condition and run-fibers completes before the fiber completes and afterwards the condition is signalled, ‘epoll instance is dead’ results.

**Comment by wingo** [comment]
Sounds like a good fix to me!

**Comment by aconchillo** [comment]
Sounds good to me too. @emixa-d can you provide a PR for this? i'll merge right away. thanks!

**Comment by emixa-d** [comment]
I've made a PR at: https://github.com/wingo/fibers/pull/62
