### ISSUE TITLE
fibers does not build without epoll

### ISSUE THREAD

**Issue by gdt** [wingo/fibers#64]
Building fibers 1.1.1 on NetBSD 9 fails because it tries to include sys/epoll.h.   This has several problems:
   - epoll.h is not specified by POSIX (and the Linux man page says that), and thus the build system should not try to include it without an autconf test
   - there doesn't seem to be an implementation using POSIX-specified facilities that is used when epoll is not present
   - the README doesn't mention this dependency -- the default expectation is that software will build on more or less "any reasonable system complying with POSIX".   (The system I'm trying to build on does have POSIX-compliant poll and also kqueue.)

**Comment by aconchillo** [comment]
See https://github.com/wingo/fibers/pull/53

**Comment by gdt** [comment]
Thank for pointing out the great news -- I will see about trying that.  It would be great if the PR were rebased, but I suppose I can fork and do that myself and then make a distfile and swap that in.

**Comment by aconchillo** [comment]
PR #53 is now rebased and ready. You should be able to use `./configure --with-libevent=yes`. I would be very interested to learn if it works. Thanks!
