### ISSUE TITLE
fibers.scm uses deprecated bitvector-set!

### ISSUE THREAD

**Issue by mwette** [wingo/fibers#66]
In guile-3.0.8 I'm getting messages regarding deprecated use of bitvector-set! (in fibers.scm).

**Comment by mwette** [comment]
Here is the full message:
```
bit-count is deprecated.  Use bitvector-count, or a loop over array-ref if array support is needed.
scm_bitvector_length is deprecated.  Use scm_c_bitvector_length instead.
bit-position is deprecated.  Use bitvector-position, or array-ref in a loop if you need generic arrays instead.
bitvector-set! is deprecated.  Use bitvector-set-bit! or bitvector-clear-bit! instead.
```

**Comment by ZelphirKaltstahl** [comment]
I am seeing the same warnings for `guile-fibers` installed via GNU Guix package manager on foreign distro `Linux Mint 20.1`. Was about to create an issue asking about the very same thing.

**Comment by aconchillo** [comment]
> Here is the full message:
> 
> ```
> bit-count is deprecated.  Use bitvector-count, or a loop over array-ref if array support is needed.
> scm_bitvector_length is deprecated.  Use scm_c_bitvector_length instead.
> bit-position is deprecated.  Use bitvector-position, or array-ref in a loop if you need generic arrays instead.
> bitvector-set! is deprecated.  Use bitvector-set-bit! or bitvector-clear-bit! instead.
> ```

Something likes this 

```
(cond-expand (guile-3 (bitvector-count group-affinity))
                       (guile-2 (bit-count #t group-affinity)))
```

would fix the warning. The problem is that the new `bitvector-*` functions where introduced in Guile 3.0.3. We could check `(version)` but it would not be as nice. May be @civodul or @emixa-d know a better way? It would be great if we had a feature per version.. or maybe that would be too much?

**Comment by emixa-d** [comment]
I was about to ask to "Don't forget Guile 1.8.", but apparently that's unsupported nowadays.

**Comment by emixa-d** [comment]
For compatibility with 3.0.0<=...<3.0.3, I propose

`(define bitvector-count* (if (defined? 'bitvector-count) bitvector-count (lambda (x) (bit-count #t x))))`

on the top-level.  Its only used during start-up, so unless there is an extreme amount of CPU units it shouldn't have a significant performance impact.

**Comment by aconchillo** [comment]
> For compatibility with 3.0.0<=...<3.0.3, I propose
> 
> `(define bitvector-count* (if (defined? 'bitvector-count) bitvector-count (lambda (x) (bit-count #t x))))`
> 
> on the top-level. Its only used during start-up, so unless there is an extreme amount of CPU units it shouldn't have a significant performance impact.

I like that. Thank you!

**Comment by aconchillo** [comment]
Ended up with

```
(define bitvector-count*
  (cond-expand
   (guile-3
    (if (defined? 'bitvector-count)
        bitvector-count
        (lambda (v) (bit-count #t v))))
   (guile-2 (lambda (v) (bit-count #t v)))))
```

Otherwise you get compilation warnings saying `bitvector-count` doesn't exist in Guile 2.
