### ISSUE TITLE
fibers depends on gnulib

### ISSUE THREAD

**Issue by gdt** [wingo/fibers#68]
I have the impression from testing the poll/libevent branch that gnulib is needed for `AC_LIB_LINKFLAGS_FROM_LIBS` but perhaps nothing more, in which case it would be nice to avoid the dependency.   Alternatively, in README where it says one needs gnulib, give a parenthetical remark about why.

**Comment by aconchillo** [comment]
`AC_LIB_LINKFLAGS_FROM_LIBS` is also defined in `gettext`. In Ubuntu 22.04 this is available in `/usr/share/aclocal/lib-link.m4`. I don't actually have `gnulib` installed.
